# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
# Download & Copy sonar.properties
  - task: DownloadSecureFile@1
    displayName: 'Fetch sonar configurations.'
    inputs:
      secureFile: 'sonar.properties'
      retryCount: '1'
  - task: CopyFiles@2
    displayName: 'Copy sonar configurations.'
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: 'sonar.properties'
      TargetFolder: $(Build.SourcesDirectory)/config
      OverWrite: true
      retryCount: '1'
# Download & Copy Firebase App Distribution Config json
  - task: DownloadSecureFile@1
    displayName: 'Fetch Firebase App Distribution Config.'
    inputs:
      secureFile: 'apps-catalog-e4a0b-140bcb296b4b.json'
      retryCount: '1'
  - task: CopyFiles@2
    displayName: 'Copy Firebase App Distribution Config.'
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: 'apps-catalog-e4a0b-140bcb296b4b.json'
      TargetFolder: $(Build.SourcesDirectory)/config
      OverWrite: true
      retryCount: '1'
# Download & Copy keystore
  - task: DownloadSecureFile@1
    displayName: 'Fetch keystore.'
    inputs:
      secureFile: 'apps_catalog_keystore'
      retryCount: '1'
  - task: CopyFiles@2
    displayName: 'Copy keystore.'
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: 'apps_catalog_keystore'
      TargetFolder: $(Build.SourcesDirectory)
      OverWrite: true
      retryCount: '1'
# Download & Copy signing.properties
  - task: DownloadSecureFile@1
    displayName: 'Fetch signing config.'
    inputs:
      secureFile: 'signing.properties'
      retryCount: '1'
  - task: CopyFiles@2
    displayName: 'Copy signing config.'
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: 'signing.properties'
      TargetFolder: $(Build.SourcesDirectory)/config
      OverWrite: true
      retryCount: '1'
  - task: JavaToolInstaller@0
    displayName: 'Setup to use JDK 17.'
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - script: |
      # Accept all SDK licenses
      yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    displayName: 'Accept all Android SDK Licenses'
  - task: Cache@2
    displayName: 'Configure gradle caching'
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts'
      restoreKeys: |
        gradle | "$(Agent.OS)"
        gradle
      path: '$(GRADLE_USER_HOME)'
  - task: Gradle@3
    displayName: 'Build (Compilation Check)'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'clean build'
  - task: Gradle@3
    displayName: 'Check code quality (Detekt).'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'detekt'
      options: '--build-cache'
  - task: Gradle@3
    displayName: 'Check code quality (Sonar Cloud)'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'sonar'
      options: '--build-cache'
  - task: Gradle@3
    displayName: 'Unit Tests'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'testDebugUnitTest'
      options: '--build-cache'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
  - task: Gradle@3
    displayName: 'UI Tests'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'runUITests'
      options: '--build-cache -Pandroid.sdk.channel=3 -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
  - task: Gradle@3
    displayName: 'Upload to Firebase App Distribution.'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'assembleDebug appDistributionUploadDebug'
      options: '--build-cache'
  - script: |
      ./gradlew --stop
    displayName: 'Stop Gradle'
